replicaCount: 3

image:
  repository: myrepo.azurecr.io/my-app
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi
